### PR TITLE
Fix compatibility issues with django >= 1.10

### PR DESCRIPTION
**Pull request by chlab**
* fix compat issue with `user.is_authenticated` (django 1.10)
* fix compat issue with missing `on_delete` setting (django 2.0)

Thanks for the package!

### CODE REVIEW

**Comment by mattijevi** [comment]
Any chance this could get merged? I can help if needed.

**Comment by chlab** [comment]
ping @pcraston - would be great, thx.

@mattijevi meanwhile I just set the requirement in my `base.in` file like so:
```
-e git://github.com/chlab/django-preventconcurrentlogins@master#egg=django-preventconcurrentlogins
```

**Comment by pcraston** [comment]
Hi! Thanks for the contribution. Been really busy recently so haven't had a chance to merge and release new version but will do soon!

**Comment by pcraston** [comment]
Hi @chlab 

Just merged the PR and pushed a new version to pypi (0.8.2).

Sorry this took so long!!!!

**Comment by chlab** [comment]
Awesome, thanks!

**Pull request merged**
